.PHONY: clean All

All:
	@echo "----------Building project:[ Zadanie8 - Debug ]----------"
	@cd "Zadanie8" && "$(MAKE)" -f  "Zadanie8.mk"
clean:
	@echo "----------Cleaning project:[ Zadanie8 - Debug ]----------"
	@cd "Zadanie8" && "$(MAKE)" -f  "Zadanie8.mk" clean
